apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: app
spec:
  type: NodePort
  selector:
    app: nginx-proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
