apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx-proxy
        image: tugceerkaner/nginx-proxy:latest
        ports:
        - containerPort: 80
